
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class dangky extends javax.swing.JFrame {

    /**
     * Creates new form dangky
     */
    user nguoidung;
    ArrayList<user> users;
    public dangky(ArrayList<user> a) {
        initComponents();
        nguoidung = new user();
        users = a;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tendangnhapjLabel = new javax.swing.JLabel();
        matkhaujLabel = new javax.swing.JLabel();
        dangkyjButton = new javax.swing.JButton();
        gioitinhjLabel = new javax.swing.JLabel();
        namjRadioButton = new javax.swing.JRadioButton();
        nujRadioButton = new javax.swing.JRadioButton();
        tendangnhapjTextField = new javax.swing.JTextField();
        TuoijLabel = new javax.swing.JLabel();
        TuoijSlider = new javax.swing.JSlider();
        showagejLabel = new javax.swing.JLabel();
        dongydieukhoangjLabel = new javax.swing.JLabel();
        dongydieukhoancheckbox = new javax.swing.JCheckBox();
        matkhauPasswordField = new javax.swing.JPasswordField();
        matkhaujLabel1 = new javax.swing.JLabel();
        nhaplaimatkhaujPasswordField = new javax.swing.JPasswordField();
        thongbaojLabel = new javax.swing.JLabel();
        DocdieukhoanjLabel = new javax.swing.JLabel();
        dieukhoanjButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Đăng ký");

        tendangnhapjLabel.setText("Tên Đăng Nhập");

        matkhaujLabel.setText("Mật khẩu");

        dangkyjButton.setText("Xác nhận đăng ký");
        dangkyjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangkyjButtonActionPerformed(evt);
            }
        });

        gioitinhjLabel.setText("Giới tính");

        buttonGroup1.add(namjRadioButton);
        namjRadioButton.setText("Nam");

        buttonGroup1.add(nujRadioButton);
        nujRadioButton.setText("Nữ");

        tendangnhapjTextField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tendangnhapjTextFieldPropertyChange(evt);
            }
        });

        TuoijLabel.setText("Tuổi");

        TuoijSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TuoijSliderStateChanged(evt);
            }
        });

        showagejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showagejLabel.setText("50");

        dongydieukhoangjLabel.setText("Tôi đồng ý với điều khoản sử dụng");

        matkhaujLabel1.setText("Nhập lại mật khẩu");

        nhaplaimatkhaujPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhaplaimatkhaujPasswordFieldActionPerformed(evt);
            }
        });

        DocdieukhoanjLabel.setText("Đọc điều khoản tại đây");

        dieukhoanjButton.setText("Điều khoản");
        dieukhoanjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dieukhoanjButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Đã có tài khoản? Đăng nhập tại đây:");

        jButton1.setText("Đăng nhập");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(thongbaojLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(matkhaujLabel)
                                    .addComponent(tendangnhapjLabel)
                                    .addComponent(matkhaujLabel1)
                                    .addComponent(gioitinhjLabel)
                                    .addComponent(TuoijLabel))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tendangnhapjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                                    .addComponent(matkhauPasswordField)
                                    .addComponent(nhaplaimatkhaujPasswordField)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(namjRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(nujRadioButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(TuoijSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(dangkyjButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dongydieukhoangjLabel)
                            .addComponent(DocdieukhoanjLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dongydieukhoancheckbox)
                            .addComponent(dieukhoanjButton))))
                .addContainerGap(32, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(showagejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(206, 206, 206))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tendangnhapjLabel)
                    .addComponent(tendangnhapjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(matkhaujLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(matkhauPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nhaplaimatkhaujPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matkhaujLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gioitinhjLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(namjRadioButton)
                        .addComponent(nujRadioButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TuoijLabel)
                    .addComponent(TuoijSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(showagejLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DocdieukhoanjLabel)
                    .addComponent(dieukhoanjButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dongydieukhoangjLabel)
                    .addComponent(dongydieukhoancheckbox))
                .addGap(7, 7, 7)
                .addComponent(dangkyjButton)
                .addGap(22, 22, 22)
                .addComponent(thongbaojLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TuoijSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TuoijSliderStateChanged
        showagejLabel.setText(String.valueOf(TuoijSlider.getValue()));
    }//GEN-LAST:event_TuoijSliderStateChanged

    private void dangkyjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangkyjButtonActionPerformed
        if(tendangnhapjTextField.getText().length()<4)
        {
            thongbaojLabel.setText("Tên đăng nhập không được dưới 4 ký tự, xin mời nhập lại");
        }
        else if (String.valueOf(matkhauPasswordField).length()<7)
        {
            thongbaojLabel.setText("Mật khẩu không được dưới 4 ký tự, xin mời nhập lại");
        }
        else if (!String.valueOf(matkhauPasswordField.getPassword()).equals(String.valueOf(nhaplaimatkhaujPasswordField.getPassword())))
        {
            thongbaojLabel.setText("Nhập lại mật khẩu sai, xin mời nhập lại");
        }
        else if (!dongydieukhoancheckbox.isSelected())
        {
            thongbaojLabel.setText("Xin mời đọc kỹ và đồng ý điều khoản");
        }
        else
        {
            nguoidung.setTendangnhap(tendangnhapjTextField.getText());
            nguoidung.setMatkhau(String.valueOf(matkhauPasswordField.getPassword()));
            nguoidung.setAge(TuoijSlider.getValue());
            nguoidung.setGender("Nam");
            this.users.add(nguoidung); 

            this.setVisible(false);
            new Interface(users).setVisible(true);
        }
        
    }//GEN-LAST:event_dangkyjButtonActionPerformed

    private void nhaplaimatkhaujPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhaplaimatkhaujPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nhaplaimatkhaujPasswordFieldActionPerformed

    private void dieukhoanjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dieukhoanjButtonActionPerformed
     
        new dieukhoan(users).setVisible(true);
    }//GEN-LAST:event_dieukhoanjButtonActionPerformed

    private void tendangnhapjTextFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tendangnhapjTextFieldPropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tendangnhapjTextFieldPropertyChange

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new Interface(users).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dangky.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dangky.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dangky.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dangky.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DocdieukhoanjLabel;
    private javax.swing.JLabel TuoijLabel;
    private javax.swing.JSlider TuoijSlider;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton dangkyjButton;
    private javax.swing.JButton dieukhoanjButton;
    private javax.swing.JCheckBox dongydieukhoancheckbox;
    private javax.swing.JLabel dongydieukhoangjLabel;
    private javax.swing.JLabel gioitinhjLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField matkhauPasswordField;
    private javax.swing.JLabel matkhaujLabel;
    private javax.swing.JLabel matkhaujLabel1;
    private javax.swing.JRadioButton namjRadioButton;
    private javax.swing.JPasswordField nhaplaimatkhaujPasswordField;
    private javax.swing.JRadioButton nujRadioButton;
    private javax.swing.JLabel showagejLabel;
    private javax.swing.JLabel tendangnhapjLabel;
    private javax.swing.JTextField tendangnhapjTextField;
    private javax.swing.JLabel thongbaojLabel;
    // End of variables declaration//GEN-END:variables
}
