
import java.awt.List;
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    ArrayList<user> users;
    user currentuser;
    public Interface(ArrayList<user> a) {
        initComponents();
        users = a;
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TênĐăngNhậpjLabel = new javax.swing.JLabel();
        TenDangNhapjTextField = new javax.swing.JTextField();
        MậtKhaujLabel = new javax.swing.JLabel();
        matkhauPasswordField = new javax.swing.JPasswordField();
        javax.swing.JLabel tittle = new javax.swing.JLabel();
        showpassjButton1 = new javax.swing.JButton();
        showpassjLabel = new javax.swing.JLabel();
        dangnhapjButton = new javax.swing.JButton();
        dangkyJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        matkhausaiJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TênĐăngNhậpjLabel.setText("Tên đăng nhập");

        MậtKhaujLabel.setText("Mật khẩu");

        matkhauPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matkhauPasswordFieldActionPerformed(evt);
            }
        });

        tittle.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        tittle.setText("Chào mừng bạn đến với thế giới Blockchain");

        showpassjButton1.setText("Show mật khẩu");
        showpassjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassjButton1ActionPerformed(evt);
            }
        });

        dangnhapjButton.setText("Đăng nhập");
        dangnhapjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangnhapjButtonActionPerformed(evt);
            }
        });

        dangkyJButton.setText("Đăng ký");
        dangkyJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangkyJButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Chưa có tài khoản ư? Đăng ký tại đây");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(dangnhapjButton)
                .addGap(126, 126, 126))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(tittle))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(dangkyJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(matkhausaiJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(MậtKhaujLabel)
                                    .addComponent(TênĐăngNhậpjLabel)
                                    .addComponent(showpassjButton1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TenDangNhapjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                    .addComponent(matkhauPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                    .addComponent(showpassjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TênĐăngNhậpjLabel)
                    .addComponent(TenDangNhapjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MậtKhaujLabel)
                    .addComponent(matkhauPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showpassjButton1)
                    .addComponent(showpassjLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(dangnhapjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(matkhausaiJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dangkyJButton)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void matkhauPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matkhauPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matkhauPasswordFieldActionPerformed

    private void showpassjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassjButton1ActionPerformed
        String s = String.valueOf(matkhauPasswordField.getPassword());
        showpassjLabel.setText(s);
    }//GEN-LAST:event_showpassjButton1ActionPerformed

    private void dangkyJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangkyJButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new dangky(users).setVisible(true);
    }//GEN-LAST:event_dangkyJButtonActionPerformed

    private void dangnhapjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangnhapjButtonActionPerformed
        int check =0;
        for(user user:users)
        {
            if (TenDangNhapjTextField.getText().equals(user.getTendangnhap())&& ((String.valueOf(matkhauPasswordField.getPassword())).equals(user.getMatkhau())))
            {
               check =1;
               currentuser =  user;
               break;
            }
        }
        if (check ==1)
        {
               
                this.setVisible(false);
                new gioithieu(users,currentuser).setVisible(true);
        }
        else
        {
            matkhausaiJLabel.setText("Tên đăng nhập hoặc mật khẩu sai, vui lòng thử lại");
        }
    }//GEN-LAST:event_dangnhapjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MậtKhaujLabel;
    private javax.swing.JTextField TenDangNhapjTextField;
    private javax.swing.JLabel TênĐăngNhậpjLabel;
    private javax.swing.JButton dangkyJButton;
    private javax.swing.JButton dangnhapjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField matkhauPasswordField;
    private javax.swing.JLabel matkhausaiJLabel;
    private javax.swing.JButton showpassjButton1;
    private javax.swing.JLabel showpassjLabel;
    // End of variables declaration//GEN-END:variables
}
