
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URI;
import java.util.ArrayList;
import java.util.Map;
import org.json.simple.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class searchengine extends javax.swing.JFrame {

    /**
     * Creates new form searchengine
     */
    ArrayList<user> users;
    public searchengine(ArrayList<user> a) {
        initComponents();
        this.users = a;
        view1.setVisible(false);
        view2.setVisible(false);
        view3.setVisible(false);
        view4.setVisible(false);
        view5.setVisible(false);
        view6.setVisible(false);
        view6.setVisible(false);
        view7.setVisible(false);
        view8.setVisible(false);
        view9.setVisible(false);
        view10.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        searchbar = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        title1 = new javax.swing.JLabel();
        view1 = new javax.swing.JButton();
        title2 = new javax.swing.JLabel();
        view2 = new javax.swing.JButton();
        title3 = new javax.swing.JLabel();
        title4 = new javax.swing.JLabel();
        title5 = new javax.swing.JLabel();
        title6 = new javax.swing.JLabel();
        view3 = new javax.swing.JButton();
        view4 = new javax.swing.JButton();
        view5 = new javax.swing.JButton();
        view6 = new javax.swing.JButton();
        title7 = new javax.swing.JLabel();
        view7 = new javax.swing.JButton();
        view8 = new javax.swing.JButton();
        title8 = new javax.swing.JLabel();
        title9 = new javax.swing.JLabel();
        view9 = new javax.swing.JButton();
        view10 = new javax.swing.JButton();
        title10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Google_2015_logo.svg.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        searchbar.setToolTipText("Type something here");

        jComboBox1.setFont(new java.awt.Font("Open Sans Medium", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Article", "Blog", " " }));

        jButton2.setLabel("Log out");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Open Sans Medium", 1, 12)); // NOI18N
        jButton1.setText("Search");
        jButton1.setToolTipText("Search gì đó đi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178)
                .addComponent(jButton2)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jLabel1))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchbar)
                    .addComponent(jButton1))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jScrollPane2.setBorder(null);

        title1.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N

        view1.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        view1.setLabel("View");
        view1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view1ActionPerformed(evt);
            }
        });

        title2.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N

        view2.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        view2.setLabel("View");
        view2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view2ActionPerformed(evt);
            }
        });

        title3.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N

        title4.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N

        title5.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N

        title6.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N

        view3.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        view3.setLabel("View");

        view4.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        view4.setLabel("View");

        view5.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        view5.setLabel("View");

        view6.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        view6.setLabel("View");

        title7.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N

        view7.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        view7.setLabel("View");

        view8.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        view8.setLabel("View");

        title8.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N

        title9.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N

        view9.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        view9.setLabel("View");

        view10.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        view10.setLabel("View");

        title10.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(view3)
                                    .addComponent(view4)
                                    .addComponent(view5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(view6)
                                    .addComponent(view7))
                                .addComponent(view2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(view1, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(view8)
                            .addComponent(view9))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(view10)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(view1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(view2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(view3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(title3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(view4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(view5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(view6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(view7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(view8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(view9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(view10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(title10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.setVisible(false);
        new searchengine(users).setVisible(true);
             
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Interface(users).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ActionListener[] listeners = view1.getActionListeners();
        for (ActionListener listener : listeners) {
        view1.removeActionListener(listener);
        }
        title1.setVisible(false);
        title2.setVisible(false);
        title3.setVisible(false);
        title4.setVisible(false);
        title5.setVisible(false);
        title6.setVisible(false);
        title7.setVisible(false);
        title8.setVisible(false);
        title9.setVisible(false);
        title10.setVisible(false);
        String input=searchbar.getText();
        sendatatoserver a= new sendatatoserver();
        JSONArray jsonarray = a.printserver(input);
        for (int i=0;i<jsonarray.size();i++)
        {
            JSONObject jsonobject = (JSONObject) jsonarray.get(i);
            if (i==1)
            {
                title1.setText((String)jsonobject.get("title"));
                title1.setVisible(true);
                view1.setVisible(true);
                view1.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                   new view((String) jsonobject.get("title"),(String) jsonobject.get("creationDate"),(String) jsonobject.get("content")).setVisible(true);
                }});
            }
            if (i==2)
            {
                title2.setText((String)jsonobject.get("title"));
                title2.setVisible(true);
                view2.setVisible(true);
                view2.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                   new view((String) jsonobject.get("title"),(String) jsonobject.get("creationDate"),(String) jsonobject.get("content")).setVisible(true);
                }});
            }
            if (i==3)
            {
                title3.setText((String)jsonobject.get("title"));
                view3.setVisible(true);
                title3.setVisible(true);
                view3.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                   new view((String) jsonobject.get("title"),(String) jsonobject.get("creationDate"),(String) jsonobject.get("content")).setVisible(true);
                }});
            }
            if (i==4)
            {
                title4.setText((String)jsonobject.get("title"));
                title4.setVisible(true);
                view4.setVisible(true);
                view4.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                   new view((String) jsonobject.get("title"),(String) jsonobject.get("creationDate"),(String) jsonobject.get("content")).setVisible(true);
                }});
            }
            if (i==5)
            {
                title5.setText((String)jsonobject.get("title"));
                title5.setVisible(true);
                view5.setVisible(true);
                view5.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                   new view((String) jsonobject.get("title"),(String) jsonobject.get("creationDate"),(String) jsonobject.get("content")).setVisible(true);
                }});
            }
            if (i==6)
            {
                title6.setText((String)jsonobject.get("title"));
                title6.setVisible(true);
                view6.setVisible(true);
                view6.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                   new view((String) jsonobject.get("title"),(String) jsonobject.get("creationDate"),(String) jsonobject.get("content")).setVisible(true);
                }});
            }
            if (i==7)
            {
                title7.setText((String)jsonobject.get("title"));
                title7.setVisible(true);
                view7.setVisible(true);
                view7.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                   new view((String) jsonobject.get("title"),(String) jsonobject.get("creationDate"),(String) jsonobject.get("content")).setVisible(true);
                }});
            }
            if (i==8)
            {
                title8.setText((String)jsonobject.get("title"));
                title8.setVisible(true);
                view8.setVisible(true);
                view8.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                   new view((String) jsonobject.get("title"),(String) jsonobject.get("creationDate"),(String) jsonobject.get("content")).setVisible(true);
                }});
            }
            if (i==9)
            {
                title9.setText((String)jsonobject.get("title"));
                title9.setVisible(true);
                view9.setVisible(true);
                view9.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                   new view((String) jsonobject.get("title"),(String) jsonobject.get("creationDate"),(String) jsonobject.get("content")).setVisible(true);
                }});
            }
            if (i==10)
            {
                title10.setText((String)jsonobject.get("title"));
                title10.setVisible(true);
                view10.setVisible(true);
                view10.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                   new view((String) jsonobject.get("title"),(String) jsonobject.get("creationDate"),(String) jsonobject.get("content")).setVisible(true);
                }});
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void view1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_view1ActionPerformed

    private void view2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_view2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchengine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchengine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchengine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchengine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField searchbar;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title10;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel title3;
    private javax.swing.JLabel title4;
    private javax.swing.JLabel title5;
    private javax.swing.JLabel title6;
    private javax.swing.JLabel title7;
    private javax.swing.JLabel title8;
    private javax.swing.JLabel title9;
    private javax.swing.JButton view1;
    private javax.swing.JButton view10;
    private javax.swing.JButton view2;
    private javax.swing.JButton view3;
    private javax.swing.JButton view4;
    private javax.swing.JButton view5;
    private javax.swing.JButton view6;
    private javax.swing.JButton view7;
    private javax.swing.JButton view8;
    private javax.swing.JButton view9;
    // End of variables declaration//GEN-END:variables
}
